version: '3.3'

services:

  server:
    container_name: "qabox_first_app"
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    environment:
      - FLASK_ENV=development
    networks:
      - samplenetwork