version: '3.3'

services:

  flask_app:
    container_name: "flask_app"
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    environment:
      - FLASK_ENV=development
    networks:
      - samplenetwork